// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

const (
	SwaggerInfoBasePath = "/api"

	// SwaggerInfo holds exported Swagger Info so clients can modify it
	SwaggerInfoHost = "localhost:3000"
	SwaggerInfoVersion = "1.0"
)
